module Ruboto
  MINIMUM_SUPPORTED_SDK_LEVEL = 7
  MINIMUM_SUPPORTED_SDK = "android-#{MINIMUM_SUPPORTED_SDK_LEVEL}"
  DEFAULT_TARGET_SDK_LEVEL = 8
  DEFAULT_TARGET_SDK = "android-#{DEFAULT_TARGET_SDK_LEVEL}"
end
